# The URL the site will be built for
base_url = "https://manta.ie"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# RSS Feed
generate_feed = true
feed_filename = "rss.xml"

taxonomies = [
    {name = "tags", feed = true}
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
title = "MANTA Lab"
title_default_tag = "Secure Asset Collaboration"
description = "Cloud-based platform for secure digital asset management, collaboration, and version control in game development, animation, and film"
logo = "manta-logo.svg"
