# On every push this script is executed
on:
  push:
    branches:
      - main

name: Build and deploy to github pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.1'

      - name: Install dependencies
        run: yarn install

      - name: Build tailwind style
        run: yarn build

      - name: build and deploy
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
